#!/bin/sh

. /etc/rc.subr

name=route53
rcvar=route53_enable

start_cmd="${name}_start"
stop_cmd=":"
load_rc_config $name

route53_start()
{
  /usr/local/bin/bash \
    /usr/local/etc/route53/aws-dyndns.bash \
    2>&1 | logger -t awsdyndns & 
}

run_rc_command "$1"
